# Generated by Django 4.2 on 2023-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
